In [11]:
import numpy as np

a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b = np.array([[[3, 4, 5], [5, 5, 9]], [[4, 8, 7], [10, 12, 9]]])
c = a + b
d = b - a
e = a * b
f = a / b
g = a % b

print("Matrix A:-")
print(a)
print()
print("Matrix B:-")
print(b)
print()
print("Addition of Matrix A and Matrix B:-")
print(c)
print()
print("Subtraction of Matrix A from Matrix B:-")
print(d)
print()
print("Multiplication of Matrix A and Matrix B:-")
print(e)
print()
print("Divison of Matrix A and Matrix B:-")
print(f)
print()
print("Modulus of Matrix A and Matrix B:-")
print(g)

Matrix A:-
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Matrix B:-
[[[ 3  4  5]
  [ 5  5  9]]

 [[ 4  8  7]
  [10 12  9]]]

Addition of Matrix A and Matrix B:-
[[[ 4  6  8]
  [ 9 10 15]]

 [[11 16 16]
  [20 23 21]]]

Subtraction of Matrix A from Matrix B:-
[[[ 2  2  2]
  [ 1  0  3]]

 [[-3  0 -2]
  [ 0  1 -3]]]

Multiplication of Matrix A and Matrix B:-
[[[  3   8  15]
  [ 20  25  54]]

 [[ 28  64  63]
  [100 132 108]]]

Divison of Matrix A and Matrix B:-
[[[0.33333333 0.5        0.6       ]
  [0.8        1.         0.66666667]]

 [[1.75       1.         1.28571429]
  [1.         0.91666667 1.33333333]]]

Modulus of Matrix A and Matrix B:-
[[[ 1  2  3]
  [ 4  0  6]]

 [[ 3  0  2]
  [ 0 11  3]]]
